INFO 2025-08-24 21:43:01,569 autoreload 23353 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 21:43:15,022 autoreload 23353 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 21:43:15,334 autoreload 23434 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 21:43:53,344 autoreload 23434 8486575872 /Applications/smart-waste-management/core/serializers.py changed, reloading.
INFO 2025-08-24 21:43:53,663 autoreload 23679 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 21:44:53,225 autoreload 23679 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-24 21:44:53,538 autoreload 24036 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 21:57:10,320 autoreload 24036 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-24 21:57:10,631 autoreload 28568 8486575872 Watching for file changes with StatReloader
WARNING 2025-08-24 21:59:06,982 log 28568 6165704704 Forbidden: /api/bin-data/
WARNING 2025-08-24 21:59:06,982 basehttp 28568 6165704704 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-24 21:59:06,984 log 28568 6165704704 Forbidden: /api/dumping-spots/
WARNING 2025-08-24 21:59:06,984 basehttp 28568 6165704704 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-24 21:59:06,986 log 28568 6165704704 Forbidden: /api/trucks/
WARNING 2025-08-24 21:59:06,986 basehttp 28568 6165704704 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-24 21:59:17,125 base 28568 6165704704 Session data corrupted
INFO 2025-08-24 21:59:17,134 basehttp 28568 6165704704 "GET /admin/ HTTP/1.1" 302 0
WARNING 2025-08-24 21:59:17,137 base 28568 6165704704 Session data corrupted
INFO 2025-08-24 21:59:17,153 basehttp 28568 6165704704 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 25507
WARNING 2025-08-24 21:59:38,523 base 28568 6165704704 Session data corrupted
INFO 2025-08-24 21:59:38,660 basehttp 28568 6165704704 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-08-24 21:59:38,672 basehttp 28568 6165704704 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:00:19,954 basehttp 28568 6165704704 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:00:42,825 autoreload 30387 8486575872 Watching for file changes with StatReloader
WARNING 2025-08-24 22:00:46,392 log 30387 6197932032 Forbidden: /api/bin-data/
WARNING 2025-08-24 22:00:46,392 basehttp 30387 6197932032 "HEAD /api/bin-data/ HTTP/1.1" 403 0
INFO 2025-08-24 22:00:51,000 basehttp 30387 6197932032 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 22:01:07,034 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:03:09,151 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:03:12,534 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:04:11,202 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:04:16,536 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:04:30,210 basehttp 30387 6197932032 "GET /admin/core/truck/ HTTP/1.1" 200 37758
INFO 2025-08-24 22:04:30,225 basehttp 30387 6197932032 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-24 22:04:36,881 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:04:41,971 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:04:42,796 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:04:43,718 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:04:50,154 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:11:35,082 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:11:36,768 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
INFO 2025-08-24 22:11:38,109 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 33195
WARNING 2025-08-24 22:11:45,356 log 30387 6197932032 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-24 22:11:45,356 basehttp 30387 6197932032 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-24 22:13:23,204 basehttp 30387 6231584768 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 22:13:38,213 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 35239
WARNING 2025-08-24 22:13:38,226 log 30387 6197932032 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-24 22:13:38,227 basehttp 30387 6197932032 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-24 22:19:26,684 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 35239
INFO 2025-08-24 22:19:43,290 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 35239
INFO 2025-08-24 22:20:10,938 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 35239
INFO 2025-08-24 22:24:18,100 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 35239
INFO 2025-08-24 22:25:55,880 basehttp 30387 6197932032 "GET /admin/ HTTP/1.1" 200 35239
INFO 2025-08-24 22:26:04,624 autoreload 30387 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 22:26:05,068 autoreload 39754 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 22:37:09,192 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 35239
INFO 2025-08-24 22:37:12,355 basehttp 39754 6190493696 "GET / HTTP/1.1" 200 4997
INFO 2025-08-24 22:37:12,377 views 39754 6190493696 Bin data retrieved by user: admin
INFO 2025-08-24 22:37:12,380 basehttp 39754 6190493696 "GET /api/bin-data/ HTTP/1.1" 200 10974
INFO 2025-08-24 22:37:35,447 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 35239
INFO 2025-08-24 22:37:41,065 basehttp 39754 6190493696 "GET /admin/password_change/ HTTP/1.1" 200 33527
INFO 2025-08-24 22:37:46,122 basehttp 39754 6190493696 "GET /admin/password_change/ HTTP/1.1" 200 33527
INFO 2025-08-24 22:37:51,578 basehttp 39754 6190493696 "POST /admin/logout/ HTTP/1.1" 200 26946
INFO 2025-08-24 22:37:54,448 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 22:37:54,458 basehttp 39754 6190493696 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 27551
INFO 2025-08-24 22:38:04,133 basehttp 39754 6190493696 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-08-24 22:38:04,139 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 35239
INFO 2025-08-24 22:38:08,323 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 35239
INFO 2025-08-24 22:38:16,628 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 35239
INFO 2025-08-24 22:42:27,676 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 40208
INFO 2025-08-24 22:42:57,087 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 40208
INFO 2025-08-24 22:43:02,151 basehttp 39754 6224146432 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 22:43:14,071 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 40208
INFO 2025-08-24 22:43:33,087 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 40526
INFO 2025-08-24 22:43:55,870 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 41422
INFO 2025-08-24 22:49:20,898 basehttp 39754 6207320064 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 22:49:31,744 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 35965
INFO 2025-08-24 22:49:40,038 basehttp 39754 6190493696 "GET /admin/auth/ HTTP/1.1" 200 33174
INFO 2025-08-24 22:49:42,071 basehttp 39754 6190493696 "GET /admin/auth/ HTTP/1.1" 200 33174
INFO 2025-08-24 22:49:42,953 basehttp 39754 6190493696 "GET /admin/auth/ HTTP/1.1" 200 33174
INFO 2025-08-24 22:49:44,020 basehttp 39754 6190493696 "GET /admin/ HTTP/1.1" 200 35965
INFO 2025-08-24 22:50:24,086 autoreload 39754 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 22:50:24,427 autoreload 48849 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 22:50:53,221 autoreload 48849 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 22:50:53,483 autoreload 49022 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 22:51:02,837 autoreload 49022 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 22:51:03,092 autoreload 49097 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 22:51:14,510 autoreload 49097 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 22:51:14,747 autoreload 49170 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 22:51:46,445 autoreload 49170 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 22:51:46,710 autoreload 49379 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 22:53:04,821 basehttp 49379 6165950464 "GET /admin/ HTTP/1.1" 200 39130
INFO 2025-08-24 22:53:11,596 basehttp 49379 6165950464 "GET /admin/ HTTP/1.1" 200 39130
INFO 2025-08-24 22:53:19,641 autoreload 49379 8486575872 /Applications/smart-waste-management/core/urls.py changed, reloading.
INFO 2025-08-24 22:53:19,989 autoreload 49968 8486575872 Watching for file changes with StatReloader
ERROR 2025-08-24 22:53:21,616 log 49968 6196850688 Internal Server Error: /admin/axes/accessattempt/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: axes_accessattempt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2024, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/options.py", line 867, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/views/main.py", line 146, in __init__
    self.get_results(request)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/views/main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: axes_accessattempt
ERROR 2025-08-24 22:53:21,620 basehttp 49968 6196850688 "GET /admin/axes/accessattempt/ HTTP/1.1" 500 202600
INFO 2025-08-24 22:53:25,033 basehttp 49968 6196850688 "GET /admin/ HTTP/1.1" 200 39130
INFO 2025-08-24 22:53:26,815 basehttp 49968 6196850688 "GET /admin/core/truck/ HTTP/1.1" 200 42963
INFO 2025-08-24 22:53:26,830 basehttp 49968 6196850688 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-24 22:53:39,204 basehttp 49968 6196850688 "GET /admin/ HTTP/1.1" 200 39130
INFO 2025-08-24 22:54:41,335 autoreload 49968 8486575872 /Applications/smart-waste-management/core/auth_backends.py changed, reloading.
INFO 2025-08-24 22:54:41,614 autoreload 50487 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 22:54:52,079 autoreload 50487 8486575872 /Applications/smart-waste-management/core/auth_backends.py changed, reloading.
INFO 2025-08-24 22:54:52,338 autoreload 50553 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 22:55:01,767 autoreload 50553 8486575872 /Applications/smart-waste-management/core/auth_backends.py changed, reloading.
INFO 2025-08-24 22:55:02,009 autoreload 50616 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 23:05:32,616 basehttp 50616 6165262336 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:07:24,515 basehttp 50616 6165262336 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:07:37,015 basehttp 50616 6165262336 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:09:04,739 autoreload 50616 8486575872 /Applications/smart-waste-management/core/urls.py changed, reloading.
INFO 2025-08-24 23:09:05,066 autoreload 55741 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 23:10:00,719 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:11:16,977 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:12:42,145 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:12:47,753 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:13:31,482 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:20:40,411 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:20:44,517 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:20:46,622 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:20:47,846 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:20:48,908 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:20:49,807 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:20:50,587 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:21:01,107 basehttp 55741 6133641216 "GET /admin/core/role/add/ HTTP/1.1" 200 41063
INFO 2025-08-24 23:21:01,124 basehttp 55741 6133641216 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-24 23:21:14,509 basehttp 55741 6133641216 "POST /admin/core/role/add/ HTTP/1.1" 200 41452
INFO 2025-08-24 23:21:14,523 basehttp 55741 6133641216 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-24 23:21:15,694 basehttp 55741 6133641216 "POST /admin/core/role/add/ HTTP/1.1" 200 41452
INFO 2025-08-24 23:21:15,706 basehttp 55741 6133641216 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-24 23:21:16,633 basehttp 55741 6133641216 "POST /admin/core/role/add/ HTTP/1.1" 200 41452
INFO 2025-08-24 23:21:16,646 basehttp 55741 6133641216 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-24 23:21:17,392 basehttp 55741 6133641216 "POST /admin/core/role/add/ HTTP/1.1" 200 41452
INFO 2025-08-24 23:21:17,409 basehttp 55741 6133641216 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-24 23:21:19,275 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:21:22,629 basehttp 55741 6133641216 "GET /admin/core/dumpingspot/add/ HTTP/1.1" 200 42907
INFO 2025-08-24 23:21:22,642 basehttp 55741 6133641216 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-24 23:21:34,505 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:21:36,653 basehttp 55741 6133641216 "GET /api/user-management/ HTTP/1.1" 200 36099
INFO 2025-08-24 23:21:47,944 basehttp 55741 6133641216 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:22:40,243 autoreload 55741 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 23:22:40,489 autoreload 60663 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 23:22:48,846 autoreload 60663 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 23:22:49,083 autoreload 60723 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 23:23:06,671 autoreload 60723 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 23:23:06,945 autoreload 60827 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 23:24:19,649 basehttp 60827 6193180672 "HEAD /api/user-management/ HTTP/1.1" 302 0
INFO 2025-08-24 23:24:31,594 autoreload 60827 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-24 23:24:31,833 autoreload 61528 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 23:24:47,925 basehttp 61528 6199980032 "GET /admin/ HTTP/1.1" 200 39254
INFO 2025-08-24 23:24:51,641 basehttp 61528 6199980032 "GET /admin/ HTTP/1.1" 200 39254
WARNING 2025-08-24 23:24:58,015 log 61528 6233632768 Forbidden: /api/bin-data/
WARNING 2025-08-24 23:24:58,016 basehttp 61528 6233632768 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-24 23:24:58,018 log 61528 6233632768 Forbidden: /api/dumping-spots/
WARNING 2025-08-24 23:24:58,018 basehttp 61528 6233632768 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-24 23:24:58,020 log 61528 6233632768 Forbidden: /api/trucks/
WARNING 2025-08-24 23:24:58,021 basehttp 61528 6233632768 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-24 23:25:20,137 log 61528 6233632768 Forbidden: /api/bin-data/
WARNING 2025-08-24 23:25:20,137 basehttp 61528 6233632768 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-24 23:25:20,141 log 61528 6233632768 Forbidden: /api/dumping-spots/
WARNING 2025-08-24 23:25:20,141 basehttp 61528 6233632768 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-24 23:25:20,143 log 61528 6233632768 Forbidden: /api/trucks/
WARNING 2025-08-24 23:25:20,143 basehttp 61528 6233632768 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-24 23:25:23,559 log 61528 6233632768 Forbidden: /api/bin-data/
WARNING 2025-08-24 23:25:23,559 basehttp 61528 6233632768 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-24 23:25:23,563 log 61528 6233632768 Forbidden: /api/dumping-spots/
WARNING 2025-08-24 23:25:23,564 basehttp 61528 6233632768 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-24 23:25:23,568 log 61528 6233632768 Forbidden: /api/trucks/
WARNING 2025-08-24 23:25:23,568 basehttp 61528 6233632768 "GET /api/trucks/ HTTP/1.1" 403 58
INFO 2025-08-24 23:25:35,603 autoreload 61528 8486575872 /Applications/smart-waste-management/core/models.py changed, reloading.
INFO 2025-08-24 23:25:35,963 autoreload 62005 8486575872 Watching for file changes with StatReloader
INFO 2025-08-24 23:29:49,068 basehttp 62005 6201126912 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 23:30:16,167 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 40382
INFO 2025-08-24 23:32:41,064 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 40382
INFO 2025-08-24 23:36:28,330 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 23:37:00,114 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 42414
INFO 2025-08-24 23:39:19,518 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 23:39:48,594 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 42439
INFO 2025-08-24 23:40:50,299 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 42437
INFO 2025-08-24 23:41:00,590 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 42437
INFO 2025-08-24 23:42:14,974 basehttp 62005 6217953280 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 23:42:30,902 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 42515
WARNING 2025-08-24 23:42:38,416 log 62005 6234779648 Forbidden: /api/bin-data/
WARNING 2025-08-24 23:42:38,416 basehttp 62005 6234779648 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-24 23:42:38,418 log 62005 6234779648 Forbidden: /api/dumping-spots/
WARNING 2025-08-24 23:42:38,418 basehttp 62005 6234779648 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-24 23:42:38,420 log 62005 6234779648 Forbidden: /api/trucks/
WARNING 2025-08-24 23:42:38,420 basehttp 62005 6234779648 "GET /api/trucks/ HTTP/1.1" 403 58
INFO 2025-08-24 23:42:47,417 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 42515
WARNING 2025-08-24 23:42:59,911 log 62005 6201126912 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-24 23:42:59,912 basehttp 62005 6201126912 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-24 23:44:46,936 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 23:45:06,478 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 42515
WARNING 2025-08-24 23:45:06,492 log 62005 6201126912 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-24 23:45:06,492 basehttp 62005 6201126912 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-24 23:46:31,485 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 23:46:57,007 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 43218
INFO 2025-08-24 23:48:36,872 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 23:49:00,517 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 52097
INFO 2025-08-24 23:50:44,475 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 52097
INFO 2025-08-24 23:51:06,945 basehttp 62005 6201126912 "GET /admin/axes/accessfailurelog/ HTTP/1.1" 200 42927
INFO 2025-08-24 23:51:06,962 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-24 23:51:10,595 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 52097
INFO 2025-08-24 23:51:29,998 basehttp 62005 6201126912 "GET /admin/core/bin/add/ HTTP/1.1" 200 47245
INFO 2025-08-24 23:51:30,017 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-24 23:51:32,921 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 52399
INFO 2025-08-24 23:54:23,848 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 23:54:43,109 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 58601
INFO 2025-08-24 23:57:28,273 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-24 23:57:46,950 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 59322
WARNING 2025-08-24 23:59:08,749 log 62005 6201126912 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-24 23:59:08,749 basehttp 62005 6201126912 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 00:01:30,422 basehttp 62005 6217953280 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:01:49,913 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 59388
WARNING 2025-08-25 00:01:49,930 log 62005 6201126912 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 00:01:49,930 basehttp 62005 6201126912 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 00:04:12,280 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:04:37,898 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 59639
INFO 2025-08-25 00:07:19,046 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:07:32,319 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 59353
INFO 2025-08-25 00:08:28,871 basehttp 62005 6201126912 "GET /admin/auth/user/ HTTP/1.1" 200 52225
INFO 2025-08-25 00:08:28,885 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:34,525 basehttp 62005 6201126912 "GET /admin/auth/user/?o=3.1 HTTP/1.1" 200 52786
INFO 2025-08-25 00:08:34,542 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:35,468 basehttp 62005 6201126912 "GET /admin/auth/user/?o=-3.1 HTTP/1.1" 200 52805
INFO 2025-08-25 00:08:35,477 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:36,049 basehttp 62005 6201126912 "GET /admin/auth/user/?o=3.1 HTTP/1.1" 200 52786
INFO 2025-08-25 00:08:36,065 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:36,640 basehttp 62005 6201126912 "GET /admin/auth/user/?o=-3.1 HTTP/1.1" 200 52805
INFO 2025-08-25 00:08:36,651 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:38,151 basehttp 62005 6201126912 "GET /admin/auth/user/?o=3.1 HTTP/1.1" 200 52794
INFO 2025-08-25 00:08:38,163 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:39,463 basehttp 62005 6201126912 "GET /admin/auth/user/?o=-3.1 HTTP/1.1" 200 52813
INFO 2025-08-25 00:08:39,480 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:40,010 basehttp 62005 6201126912 "GET /admin/auth/user/?o=3.1 HTTP/1.1" 200 52794
INFO 2025-08-25 00:08:40,023 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:40,597 basehttp 62005 6201126912 "GET /admin/auth/user/?o=-3.1 HTTP/1.1" 200 52813
INFO 2025-08-25 00:08:40,610 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:41,278 basehttp 62005 6201126912 "GET /admin/auth/user/?o=4.-3.1 HTTP/1.1" 200 53159
INFO 2025-08-25 00:08:41,297 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:43,140 basehttp 62005 6201126912 "GET /admin/auth/user/?o=-4.-3.1 HTTP/1.1" 200 53180
INFO 2025-08-25 00:08:43,157 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:43,792 basehttp 62005 6201126912 "GET /admin/auth/user/?o=4.-3.1 HTTP/1.1" 200 53159
INFO 2025-08-25 00:08:43,812 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:43,951 basehttp 62005 6201126912 "GET /admin/auth/user/?o=-4.-3.1 HTTP/1.1" 200 53180
INFO 2025-08-25 00:08:43,962 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:08:44,638 basehttp 62005 6201126912 "GET /admin/auth/user/?o=3.-4.1 HTTP/1.1" 200 53159
INFO 2025-08-25 00:08:44,660 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:11:00,709 basehttp 62005 6201126912 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:11:18,860 basehttp 62005 6201126912 "GET /admin/auth/user/?o=3.-4.1 HTTP/1.1" 200 53349
INFO 2025-08-25 00:11:18,872 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:11:21,040 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 59624
INFO 2025-08-25 00:12:26,584 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:14:05,334 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:14:24,437 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 70725
INFO 2025-08-25 00:15:55,582 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 70004
INFO 2025-08-25 00:16:00,109 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:19:32,786 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:19:52,048 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 70068
INFO 2025-08-25 00:21:38,178 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 70068
WARNING 2025-08-25 00:25:05,855 log 62005 6217953280 Forbidden: /api/bin-data/
WARNING 2025-08-25 00:25:05,855 basehttp 62005 6217953280 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 00:25:05,857 log 62005 6217953280 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 00:25:05,857 basehttp 62005 6217953280 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 00:25:05,859 log 62005 6217953280 Forbidden: /api/trucks/
WARNING 2025-08-25 00:25:05,859 basehttp 62005 6217953280 "GET /api/trucks/ HTTP/1.1" 403 58
INFO 2025-08-25 00:25:34,540 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 70086
INFO 2025-08-25 00:26:28,813 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 70087
INFO 2025-08-25 00:26:32,225 basehttp 62005 6201126912 "GET /admin/auth/group/ HTTP/1.1" 200 59212
INFO 2025-08-25 00:26:32,243 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:26:34,661 basehttp 62005 6201126912 "GET /admin/auth/user/ HTTP/1.1" 200 62801
INFO 2025-08-25 00:26:34,675 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:26:39,512 basehttp 62005 6201126912 "GET /admin/axes/accessfailurelog/ HTTP/1.1" 200 60832
INFO 2025-08-25 00:26:39,529 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:26:42,421 basehttp 62005 6201126912 "GET /admin/core/bin/ HTTP/1.1" 200 88836
INFO 2025-08-25 00:26:42,435 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:26:57,702 basehttp 62005 6201126912 "GET /admin/core/truck/ HTTP/1.1" 200 65180
INFO 2025-08-25 00:26:57,719 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:27:00,235 basehttp 62005 6201126912 "GET /admin/core/dumpingspot/ HTTP/1.1" 200 65576
INFO 2025-08-25 00:27:00,253 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:27:02,217 basehttp 62005 6201126912 "GET /admin/core/role/ HTTP/1.1" 200 64837
INFO 2025-08-25 00:27:02,237 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:27:04,777 basehttp 62005 6201126912 "GET /admin/core/bin/ HTTP/1.1" 200 88836
INFO 2025-08-25 00:27:04,791 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:27:44,950 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:28:02,421 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 70087
INFO 2025-08-25 00:28:05,630 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 70087
WARNING 2025-08-25 00:28:28,700 log 62005 6201126912 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 00:28:28,700 basehttp 62005 6201126912 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 00:31:16,639 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:31:45,675 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 71729
WARNING 2025-08-25 00:31:45,689 log 62005 6201126912 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 00:31:45,689 basehttp 62005 6201126912 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
WARNING 2025-08-25 00:32:26,044 log 62005 6201126912 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 00:32:26,044 basehttp 62005 6201126912 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 00:39:39,009 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 71836
WARNING 2025-08-25 00:39:39,026 log 62005 6201126912 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 00:39:39,026 basehttp 62005 6201126912 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 00:40:00,999 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 72279
INFO 2025-08-25 00:40:07,298 basehttp 62005 6234779648 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:40:55,766 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 72279
WARNING 2025-08-25 00:41:07,725 log 62005 6201126912 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 00:41:07,725 basehttp 62005 6201126912 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 00:43:16,393 basehttp 62005 6201126912 "HEAD /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 00:43:29,094 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 72906
WARNING 2025-08-25 00:48:14,330 log 62005 6217953280 Forbidden: /api/bin-data/
WARNING 2025-08-25 00:48:14,330 basehttp 62005 6217953280 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 00:48:14,332 log 62005 6217953280 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 00:48:14,332 basehttp 62005 6217953280 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 00:48:14,334 log 62005 6217953280 Forbidden: /api/trucks/
WARNING 2025-08-25 00:48:14,334 basehttp 62005 6217953280 "GET /api/trucks/ HTTP/1.1" 403 58
INFO 2025-08-25 00:52:42,492 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 73235
INFO 2025-08-25 00:53:58,769 basehttp 62005 6201126912 "GET /api/user-management/ HTTP/1.1" 200 61464
INFO 2025-08-25 00:54:09,794 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 73235
INFO 2025-08-25 00:54:16,726 basehttp 62005 6201126912 "GET /admin/core/bin/add/ HTTP/1.1" 200 67996
INFO 2025-08-25 00:54:16,743 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 00:54:19,719 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 73235
INFO 2025-08-25 00:54:20,647 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 73235
INFO 2025-08-25 01:03:52,576 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 73383
INFO 2025-08-25 01:04:03,466 basehttp 62005 6201126912 "GET /admin/auth/ HTTP/1.1" 200 65730
INFO 2025-08-25 01:04:05,350 basehttp 62005 6201126912 "GET /admin/auth/ HTTP/1.1" 200 65730
INFO 2025-08-25 01:05:05,092 basehttp 62005 6201126912 "GET /admin/auth/ HTTP/1.1" 200 67888
INFO 2025-08-25 01:07:22,298 basehttp 62005 6201126912 "GET /admin/auth/ HTTP/1.1" 200 71688
INFO 2025-08-25 01:09:12,850 basehttp 62005 6201126912 "GET /admin/auth/ HTTP/1.1" 200 65730
INFO 2025-08-25 01:09:20,058 basehttp 62005 6201126912 "GET /admin/auth/ HTTP/1.1" 200 65730
INFO 2025-08-25 01:09:33,313 basehttp 62005 6201126912 "GET /admin/auth/ HTTP/1.1" 200 65730
INFO 2025-08-25 01:10:43,159 basehttp 62005 6201126912 "GET /admin/auth/ HTTP/1.1" 200 70659
INFO 2025-08-25 01:11:45,361 basehttp 62005 6201126912 "GET /admin/core/bin/add/ HTTP/1.1" 200 75032
INFO 2025-08-25 01:11:45,375 basehttp 62005 6201126912 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 01:11:50,967 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 80271
INFO 2025-08-25 01:12:12,295 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 82253
INFO 2025-08-25 01:12:25,312 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 82253
INFO 2025-08-25 01:12:47,912 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 82253
INFO 2025-08-25 01:15:19,901 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 82699
INFO 2025-08-25 01:15:42,721 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 82723
INFO 2025-08-25 01:19:26,598 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 81423
INFO 2025-08-25 01:19:44,203 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 81202
INFO 2025-08-25 01:21:20,452 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 78881
INFO 2025-08-25 01:24:19,033 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 76960
INFO 2025-08-25 01:28:22,585 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 77008
INFO 2025-08-25 01:28:41,684 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 77008
INFO 2025-08-25 01:34:45,140 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 77465
INFO 2025-08-25 01:37:18,775 basehttp 62005 6201126912 "GET /admin/ HTTP/1.1" 200 77857
INFO 2025-08-25 01:59:29,143 autoreload 62005 8486575872 /Applications/smart-waste-management/waste_management/urls.py changed, reloading.
INFO 2025-08-25 01:59:29,528 autoreload 58472 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 01:59:44,025 autoreload 58472 8486575872 /Applications/smart-waste-management/core/admin.py changed, reloading.
INFO 2025-08-25 01:59:44,272 autoreload 58582 8486575872 Watching for file changes with StatReloader
ERROR 2025-08-25 02:00:51,754 log 58582 6197260288 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/smart-waste-management/core/admin.py", line 42, in index
    avg_fill_level_spots = DumpingSpot.objects.aggregate(avg_fill=Avg('current_fill_level'))['avg_fill'] or 0
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/query.py", line 588, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/query.py", line 460, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/aggregates.py", line 63, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/expressions.py", line 300, in resolve_expression
    expr.resolve_expression(query, allow_joins, reuse, summarize, for_save)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/expressions.py", line 902, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2049, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1900, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'current_fill_level' into field. Choices are: id, latitude, longitude, metal_content, organic_content, plastic_content, spot_id, total_capacity
ERROR 2025-08-25 02:00:51,759 basehttp 58582 6197260288 "GET /admin/ HTTP/1.1" 500 148054
ERROR 2025-08-25 02:01:10,904 log 58582 6197260288 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/smart-waste-management/core/admin.py", line 42, in index
    avg_fill_level_spots = DumpingSpot.objects.aggregate(avg_fill=Avg('current_fill_level'))['avg_fill'] or 0
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/query.py", line 588, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/query.py", line 460, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/aggregates.py", line 63, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/expressions.py", line 300, in resolve_expression
    expr.resolve_expression(query, allow_joins, reuse, summarize, for_save)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/expressions.py", line 902, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2049, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1900, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'current_fill_level' into field. Choices are: id, latitude, longitude, metal_content, organic_content, plastic_content, spot_id, total_capacity
ERROR 2025-08-25 02:01:10,906 basehttp 58582 6197260288 "GET /admin/ HTTP/1.1" 500 148054
INFO 2025-08-25 02:02:19,116 autoreload 58582 8486575872 /Applications/smart-waste-management/waste_management/urls.py changed, reloading.
INFO 2025-08-25 02:02:19,359 autoreload 59560 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:02:33,784 autoreload 59560 8486575872 /Applications/smart-waste-management/core/admin.py changed, reloading.
INFO 2025-08-25 02:02:34,018 autoreload 59677 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:08:51,749 autoreload 59677 8486575872 /Applications/smart-waste-management/waste_management/urls.py changed, reloading.
INFO 2025-08-25 02:08:52,126 autoreload 61921 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:09:17,774 autoreload 61921 8486575872 /Applications/smart-waste-management/waste_management/urls.py changed, reloading.
INFO 2025-08-25 02:09:18,099 autoreload 62099 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:09:27,489 autoreload 62099 8486575872 /Applications/smart-waste-management/core/admin.py changed, reloading.
INFO 2025-08-25 02:09:27,728 autoreload 62173 8486575872 Watching for file changes with StatReloader
ERROR 2025-08-25 02:10:16,439 log 62173 6200127488 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'core_role_add' not found. 'core_role_add' is not a valid view function or pattern name.
ERROR 2025-08-25 02:10:16,441 basehttp 62173 6200127488 "GET /admin/ HTTP/1.1" 500 222754
ERROR 2025-08-25 02:14:51,184 log 62173 6200127488 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'core_role_add' not found. 'core_role_add' is not a valid view function or pattern name.
ERROR 2025-08-25 02:14:51,186 basehttp 62173 6200127488 "GET /admin/ HTTP/1.1" 500 222754
INFO 2025-08-25 02:17:35,936 autoreload 62173 8486575872 /Applications/smart-waste-management/core/admin.py changed, reloading.
INFO 2025-08-25 02:17:36,373 autoreload 65277 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:17:47,812 autoreload 65277 8486575872 /Applications/smart-waste-management/core/admin.py changed, reloading.
INFO 2025-08-25 02:17:48,039 autoreload 65362 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:17:55,347 autoreload 65362 8486575872 /Applications/smart-waste-management/core/admin.py changed, reloading.
INFO 2025-08-25 02:17:55,575 autoreload 65421 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:18:02,893 autoreload 65421 8486575872 /Applications/smart-waste-management/core/admin.py changed, reloading.
INFO 2025-08-25 02:18:03,130 autoreload 65467 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:18:10,456 autoreload 65467 8486575872 /Applications/smart-waste-management/core/admin.py changed, reloading.
INFO 2025-08-25 02:18:10,688 autoreload 65528 8486575872 Watching for file changes with StatReloader
ERROR 2025-08-25 02:18:21,807 log 65528 6203043840 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'core_role_add' not found. 'core_role_add' is not a valid view function or pattern name.
ERROR 2025-08-25 02:18:21,809 basehttp 65528 6203043840 "GET /admin/ HTTP/1.1" 500 222754
INFO 2025-08-25 02:18:22,115 autoreload 65528 8486575872 /Applications/smart-waste-management/core/admin.py changed, reloading.
INFO 2025-08-25 02:18:22,370 autoreload 65597 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:20:51,619 autoreload 67341 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:20:59,468 basehttp 65597 6167965696 "GET /admin/ HTTP/1.1" 200 69747
INFO 2025-08-25 02:20:59,563 autoreload 65597 8486575872 /Applications/smart-waste-management/core/admin.py changed, reloading.
INFO 2025-08-25 02:20:59,830 autoreload 67441 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 02:21:33,624 basehttp 67441 6164099072 "GET /admin/ HTTP/1.1" 200 69747
WARNING 2025-08-25 02:21:48,329 log 67441 6164099072 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 02:21:48,329 basehttp 67441 6164099072 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 02:24:31,750 basehttp 67441 6164099072 "GET /admin/core/role/add/ HTTP/1.1" 200 68103
WARNING 2025-08-25 02:24:31,776 log 67441 6180925440 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 02:24:31,776 basehttp 67441 6180925440 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 02:24:31,777 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:25:22,839 basehttp 67441 6164099072 "POST /admin/core/role/add/ HTTP/1.1" 200 68508
INFO 2025-08-25 02:25:22,858 basehttp 67441 6180925440 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
WARNING 2025-08-25 02:25:22,860 log 67441 6164099072 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 02:25:22,860 basehttp 67441 6164099072 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 02:25:39,341 basehttp 67441 6164099072 "POST /admin/core/role/add/ HTTP/1.1" 200 68507
WARNING 2025-08-25 02:25:39,361 log 67441 6164099072 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 02:25:39,362 basehttp 67441 6164099072 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 02:25:39,363 basehttp 67441 6180925440 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:25:40,295 basehttp 67441 6180925440 "POST /admin/core/role/add/ HTTP/1.1" 200 68507
WARNING 2025-08-25 02:25:40,317 log 67441 6180925440 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 02:25:40,318 basehttp 67441 6180925440 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 02:25:40,319 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:25:53,822 basehttp 67441 6164099072 "POST /admin/core/role/add/ HTTP/1.1" 200 68507
WARNING 2025-08-25 02:25:53,839 log 67441 6164099072 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 02:25:53,839 basehttp 67441 6164099072 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 02:25:53,841 basehttp 67441 6180925440 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:25:54,841 basehttp 67441 6180925440 "POST /admin/core/role/add/ HTTP/1.1" 200 68507
WARNING 2025-08-25 02:25:54,862 log 67441 6180925440 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 02:25:54,862 basehttp 67441 6180925440 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 02:25:54,863 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:26:01,715 basehttp 67441 6164099072 "POST /admin/core/role/add/ HTTP/1.1" 200 68509
WARNING 2025-08-25 02:26:01,736 log 67441 6164099072 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 02:26:01,737 basehttp 67441 6164099072 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 02:26:01,738 basehttp 67441 6180925440 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:26:03,883 basehttp 67441 6180925440 "POST /admin/core/role/add/ HTTP/1.1" 200 68509
WARNING 2025-08-25 02:26:03,907 log 67441 6180925440 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-08-25 02:26:03,908 basehttp 67441 6180925440 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2633
INFO 2025-08-25 02:26:03,909 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:26:27,176 basehttp 67441 6164099072 "GET /admin/ HTTP/1.1" 200 70545
INFO 2025-08-25 02:26:43,070 basehttp 67441 6164099072 "GET /admin/ HTTP/1.1" 200 70545
INFO 2025-08-25 02:26:59,778 basehttp 67441 6164099072 "GET /admin/core/bin/ HTTP/1.1" 200 93659
INFO 2025-08-25 02:26:59,792 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:27:21,759 basehttp 67441 6164099072 "GET /admin/core/bin/?q=BIN027 HTTP/1.1" 200 71208
INFO 2025-08-25 02:27:21,775 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:27:29,135 basehttp 67441 6164099072 "GET /admin/core/bin/27/change/?_changelist_filters=q%3DBIN027 HTTP/1.1" 200 70157
INFO 2025-08-25 02:27:29,152 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:27:38,021 basehttp 67441 6164099072 "GET /admin/core/bin/?q=BIN027 HTTP/1.1" 200 71208
INFO 2025-08-25 02:27:39,660 basehttp 67441 6164099072 "GET /admin/ HTTP/1.1" 200 70545
INFO 2025-08-25 02:27:51,828 basehttp 67441 6164099072 "GET /admin/core/bin/add/ HTTP/1.1" 200 69671
INFO 2025-08-25 02:27:51,842 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:28:30,687 basehttp 67441 6164099072 "POST /admin/core/bin/add/ HTTP/1.1" 200 70092
INFO 2025-08-25 02:28:30,699 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:29:05,333 basehttp 67441 6164099072 "POST /admin/core/bin/add/ HTTP/1.1" 200 70098
INFO 2025-08-25 02:29:05,347 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:29:24,533 basehttp 67441 6164099072 "POST /admin/core/bin/add/ HTTP/1.1" 200 69932
INFO 2025-08-25 02:29:24,543 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:29:31,368 basehttp 67441 6164099072 "POST /admin/core/bin/add/ HTTP/1.1" 200 69932
INFO 2025-08-25 02:29:31,385 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:29:46,431 basehttp 67441 6164099072 "POST /admin/core/bin/add/ HTTP/1.1" 302 0
INFO 2025-08-25 02:29:46,460 basehttp 67441 6164099072 "GET /admin/core/bin/ HTTP/1.1" 200 94475
INFO 2025-08-25 02:29:46,474 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:30:10,367 basehttp 67441 6164099072 "GET /admin/core/bin/? HTTP/1.1" 200 94279
INFO 2025-08-25 02:30:10,386 basehttp 67441 6164099072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-25 02:30:16,936 basehttp 67441 6164099072 "GET /admin/ HTTP/1.1" 200 70545
INFO 2025-08-25 02:31:28,480 autoreload 67441 8486575872 /Applications/smart-waste-management/waste_management/urls.py changed, reloading.
INFO 2025-08-25 02:31:28,862 autoreload 72392 8486575872 Watching for file changes with StatReloader
WARNING 2025-08-25 02:31:53,777 log 72392 6139998208 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:31:53,777 basehttp 72392 6139998208 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:31:53,780 log 72392 6139998208 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:31:53,780 basehttp 72392 6139998208 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:31:53,782 log 72392 6139998208 Forbidden: /api/trucks/
WARNING 2025-08-25 02:31:53,782 basehttp 72392 6139998208 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:32:51,718 log 72392 6139998208 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:32:51,718 basehttp 72392 6139998208 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:32:51,720 log 72392 6139998208 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:32:51,720 basehttp 72392 6139998208 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:32:51,722 log 72392 6139998208 Forbidden: /api/trucks/
WARNING 2025-08-25 02:32:51,722 basehttp 72392 6139998208 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:33:02,953 log 72392 6139998208 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:33:02,954 basehttp 72392 6139998208 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:33:02,958 log 72392 6139998208 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:33:02,958 basehttp 72392 6139998208 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:33:02,960 log 72392 6139998208 Forbidden: /api/trucks/
WARNING 2025-08-25 02:33:02,960 basehttp 72392 6139998208 "GET /api/trucks/ HTTP/1.1" 403 58
INFO 2025-08-25 02:33:44,246 basehttp 72392 6123171840 "GET /admin/ HTTP/1.1" 200 70545
INFO 2025-08-25 02:33:49,988 basehttp 72392 6123171840 "GET / HTTP/1.1" 200 4997
INFO 2025-08-25 02:33:50,011 views 72392 6123171840 Bin data retrieved by user: admin
INFO 2025-08-25 02:33:50,014 basehttp 72392 6123171840 "GET /api/bin-data/ HTTP/1.1" 200 11176
INFO 2025-08-25 02:33:56,247 basehttp 72392 6123171840 "GET /admin/ HTTP/1.1" 200 70545
WARNING 2025-08-25 02:34:02,081 log 72392 6156824576 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:34:02,081 basehttp 72392 6156824576 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:02,083 log 72392 6156824576 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:34:02,084 basehttp 72392 6156824576 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:02,085 log 72392 6156824576 Forbidden: /api/trucks/
WARNING 2025-08-25 02:34:02,086 basehttp 72392 6156824576 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:05,107 log 72392 6156824576 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:34:05,107 basehttp 72392 6156824576 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:05,109 log 72392 6156824576 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:34:05,109 basehttp 72392 6156824576 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:05,111 log 72392 6156824576 Forbidden: /api/trucks/
WARNING 2025-08-25 02:34:05,111 basehttp 72392 6156824576 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:07,934 log 72392 6156824576 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:34:07,934 basehttp 72392 6156824576 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:07,936 log 72392 6156824576 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:34:07,936 basehttp 72392 6156824576 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:07,938 log 72392 6156824576 Forbidden: /api/trucks/
WARNING 2025-08-25 02:34:07,938 basehttp 72392 6156824576 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:19,463 log 72392 6156824576 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:34:19,463 basehttp 72392 6156824576 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:19,465 log 72392 6156824576 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:34:19,465 basehttp 72392 6156824576 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:19,467 log 72392 6156824576 Forbidden: /api/trucks/
WARNING 2025-08-25 02:34:19,467 basehttp 72392 6156824576 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:38,249 log 72392 6156824576 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:34:38,250 basehttp 72392 6156824576 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:38,253 log 72392 6156824576 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:34:38,253 basehttp 72392 6156824576 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:38,255 log 72392 6156824576 Forbidden: /api/trucks/
WARNING 2025-08-25 02:34:38,255 basehttp 72392 6156824576 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:54,167 log 72392 6139998208 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:34:54,167 basehttp 72392 6139998208 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:54,169 log 72392 6139998208 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:34:54,169 basehttp 72392 6139998208 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:54,171 log 72392 6139998208 Forbidden: /api/trucks/
WARNING 2025-08-25 02:34:54,171 basehttp 72392 6139998208 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:54,197 log 72392 6139998208 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:34:54,197 basehttp 72392 6139998208 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:54,199 log 72392 6139998208 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:34:54,199 basehttp 72392 6139998208 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:34:54,202 log 72392 6139998208 Forbidden: /api/trucks/
WARNING 2025-08-25 02:34:54,202 basehttp 72392 6139998208 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:35:01,066 log 72392 6139998208 Forbidden: /api/bin-data/
WARNING 2025-08-25 02:35:01,067 basehttp 72392 6139998208 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:35:01,069 log 72392 6139998208 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 02:35:01,069 basehttp 72392 6139998208 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 02:35:01,071 log 72392 6139998208 Forbidden: /api/trucks/
WARNING 2025-08-25 02:35:01,071 basehttp 72392 6139998208 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 03:19:58,263 log 72392 6123171840 Forbidden: /api/bin-data/
WARNING 2025-08-25 03:19:58,263 basehttp 72392 6123171840 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 03:19:58,268 log 72392 6123171840 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 03:19:58,268 basehttp 72392 6123171840 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 03:19:58,270 log 72392 6123171840 Forbidden: /api/trucks/
WARNING 2025-08-25 03:19:58,270 basehttp 72392 6123171840 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:00:36,141 log 6853 6140014592 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:00:36,141 basehttp 6853 6140014592 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:00:36,144 log 6853 6140014592 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:00:36,144 basehttp 6853 6140014592 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:00:36,146 log 6853 6140014592 Forbidden: /api/trucks/
WARNING 2025-08-25 04:00:36,147 basehttp 6853 6140014592 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:02:22,048 log 7804 6148141056 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:02:22,049 basehttp 7804 6148141056 "GET /api/bin-data/ HTTP/1.1" 403 58
INFO 2025-08-25 04:02:22,055 basehttp 7804 6148141056 "GET /api/dumping-spots/ HTTP/1.1" 200 1194
INFO 2025-08-25 04:02:22,059 basehttp 7804 6148141056 "GET /api/trucks/ HTTP/1.1" 200 900
WARNING 2025-08-25 04:03:04,869 log 7804 6148141056 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:03:04,869 basehttp 7804 6148141056 "GET /api/bin-data/ HTTP/1.1" 403 58
INFO 2025-08-25 04:03:04,872 basehttp 7804 6148141056 "GET /api/dumping-spots/ HTTP/1.1" 200 1194
INFO 2025-08-25 04:03:04,876 basehttp 7804 6148141056 "GET /api/trucks/ HTTP/1.1" 200 900
INFO 2025-08-25 04:05:19,761 basehttp 7804 6148141056 "GET /admin/ HTTP/1.1" 302 0
ERROR 2025-08-25 04:05:19,798 log 7804 6148141056 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:05:19,801 basehttp 7804 6148141056 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 163956
ERROR 2025-08-25 04:05:23,527 log 7804 6148141056 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:05:23,529 basehttp 7804 6148141056 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 163956
INFO 2025-08-25 04:07:05,402 autoreload 10024 8486575872 Watching for file changes with StatReloader
ERROR 2025-08-25 04:07:11,958 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:07:11,961 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
ERROR 2025-08-25 04:07:14,933 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:07:14,935 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
ERROR 2025-08-25 04:07:19,165 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:07:19,166 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
ERROR 2025-08-25 04:08:18,820 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:08:18,823 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
WARNING 2025-08-25 04:14:12,665 log 10024 6173880320 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:14:12,666 basehttp 10024 6173880320 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:14:12,671 log 10024 6173880320 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:14:12,672 basehttp 10024 6173880320 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:14:12,675 log 10024 6173880320 Forbidden: /api/trucks/
WARNING 2025-08-25 04:14:12,676 basehttp 10024 6173880320 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:14:25,348 log 10024 6173880320 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:14:25,349 basehttp 10024 6173880320 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:14:25,352 log 10024 6173880320 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:14:25,352 basehttp 10024 6173880320 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:14:25,355 log 10024 6173880320 Forbidden: /api/trucks/
WARNING 2025-08-25 04:14:25,356 basehttp 10024 6173880320 "GET /api/trucks/ HTTP/1.1" 403 58
ERROR 2025-08-25 04:14:35,017 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:14:35,019 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
ERROR 2025-08-25 04:14:37,727 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:14:37,729 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
ERROR 2025-08-25 04:14:43,715 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:14:43,717 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
ERROR 2025-08-25 04:14:49,427 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:14:49,429 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
INFO 2025-08-25 04:15:01,499 basehttp 10024 6157053952 "GET /admin/ HTTP/1.1" 302 0
ERROR 2025-08-25 04:15:01,526 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:15:01,528 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160154
ERROR 2025-08-25 04:15:44,677 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:15:44,678 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
WARNING 2025-08-25 04:15:50,763 log 10024 13035925504 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:15:50,764 basehttp 10024 13035925504 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:15:50,768 log 10024 13035925504 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:15:50,769 basehttp 10024 13035925504 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:15:50,778 log 10024 13035925504 Forbidden: /api/trucks/
WARNING 2025-08-25 04:15:50,778 basehttp 10024 13035925504 "GET /api/trucks/ HTTP/1.1" 403 58
ERROR 2025-08-25 04:18:46,316 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:18:46,318 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
ERROR 2025-08-25 04:23:27,584 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:23:27,585 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
ERROR 2025-08-25 04:25:02,059 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:25:02,061 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
WARNING 2025-08-25 04:25:08,483 log 10024 13035925504 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:25:08,483 basehttp 10024 13035925504 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:25:08,488 log 10024 13035925504 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:25:08,488 basehttp 10024 13035925504 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:25:08,492 log 10024 13035925504 Forbidden: /api/trucks/
WARNING 2025-08-25 04:25:08,493 basehttp 10024 13035925504 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:26:05,212 log 10024 6173880320 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:26:05,212 basehttp 10024 6173880320 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:26:05,215 log 10024 6173880320 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:26:05,215 basehttp 10024 6173880320 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:26:05,219 log 10024 6173880320 Forbidden: /api/trucks/
WARNING 2025-08-25 04:26:05,220 basehttp 10024 6173880320 "GET /api/trucks/ HTTP/1.1" 403 58
ERROR 2025-08-25 04:30:01,480 log 10024 6157053952 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/retry.py", line 105, in call_with_retry
    return do()
           ^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 803, in _connect
    raise err
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 787, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/decorators.py", line 23, in wrapper
    if utils.is_already_locked(request, username=username):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 411, in is_already_locked
    ip_blocked = is_source_ip_already_locked(get_ip(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/defender/utils.py", line 404, in is_source_ip_already_locked
    return REDIS_SERVER.get(get_ip_blocked_cache_key(ip_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/utils.py", line 195, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 1533, in get_connection
    connection.connect()
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
  File "/Users/jamstanleyambe/miniforge3/lib/python3.12/site-packages/redis/connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
ERROR 2025-08-25 04:30:01,482 basehttp 10024 6157053952 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 160291
INFO 2025-08-25 04:30:29,877 autoreload 10024 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-25 04:30:30,316 autoreload 19219 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 04:30:49,241 autoreload 19219 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-25 04:30:49,596 autoreload 19368 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 04:30:54,992 autoreload 19368 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-25 04:30:55,241 autoreload 19414 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 04:31:02,646 autoreload 19414 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-25 04:31:02,925 autoreload 19458 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 04:31:03,583 basehttp 19458 6126661632 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 59062
INFO 2025-08-25 04:31:11,388 auth_backends 19458 6126661632 Successful login: admin from 127.0.0.1
INFO 2025-08-25 04:31:11,394 basehttp 19458 6126661632 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-08-25 04:31:11,408 basehttp 19458 6126661632 "GET /admin/ HTTP/1.1" 200 70545
WARNING 2025-08-25 04:31:34,201 log 19458 6160314368 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:31:34,201 basehttp 19458 6160314368 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:31:34,205 log 19458 6160314368 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:31:34,205 basehttp 19458 6160314368 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:31:34,210 log 19458 6160314368 Forbidden: /api/trucks/
WARNING 2025-08-25 04:31:34,210 basehttp 19458 6160314368 "GET /api/trucks/ HTTP/1.1" 403 58
INFO 2025-08-25 04:31:45,369 autoreload 20114 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 04:31:52,696 autoreload 20114 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-25 04:31:52,938 autoreload 20175 8486575872 Watching for file changes with StatReloader
WARNING 2025-08-25 04:31:57,333 log 20175 6124892160 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:31:57,333 basehttp 20175 6124892160 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:31:57,336 log 20175 6124892160 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:31:57,336 basehttp 20175 6124892160 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:31:57,338 log 20175 6124892160 Forbidden: /api/trucks/
WARNING 2025-08-25 04:31:57,338 basehttp 20175 6124892160 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:32:10,796 log 20175 6124892160 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:32:10,796 basehttp 20175 6124892160 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:32:10,798 log 20175 6124892160 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:32:10,798 basehttp 20175 6124892160 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:32:10,800 log 20175 6124892160 Forbidden: /api/trucks/
WARNING 2025-08-25 04:32:10,800 basehttp 20175 6124892160 "GET /api/trucks/ HTTP/1.1" 403 58
INFO 2025-08-25 04:32:50,351 autoreload 20175 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 04:32:50,714 autoreload 20536 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 04:33:02,228 autoreload 20536 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 04:33:02,569 autoreload 20624 8486575872 Watching for file changes with StatReloader
WARNING 2025-08-25 04:33:05,228 log 20624 6171013120 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:33:05,229 basehttp 20624 6171013120 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:33:05,231 log 20624 6171013120 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:33:05,231 basehttp 20624 6171013120 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:33:05,233 log 20624 6171013120 Forbidden: /api/trucks/
WARNING 2025-08-25 04:33:05,233 basehttp 20624 6171013120 "GET /api/trucks/ HTTP/1.1" 403 58
INFO 2025-08-25 04:33:09,556 basehttp 20624 6171013120 "GET /admin/ HTTP/1.1" 200 70545
INFO 2025-08-25 04:33:12,087 autoreload 20624 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 04:33:12,423 autoreload 20686 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 04:33:22,863 autoreload 20686 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 04:33:23,095 autoreload 20753 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 04:33:32,449 autoreload 20753 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 04:33:32,682 autoreload 20830 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 04:36:20,646 autoreload 20830 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 04:36:21,022 autoreload 22305 8486575872 Watching for file changes with StatReloader
WARNING 2025-08-25 04:36:23,193 log 22305 6131331072 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:36:23,193 basehttp 22305 6131331072 "GET /api/bin-data/ HTTP/1.1" 403 58
INFO 2025-08-25 04:36:23,198 basehttp 22305 6131331072 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 04:36:23,202 basehttp 22305 6131331072 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 04:36:32,668 basehttp 22305 6131331072 "GET /admin/ HTTP/1.1" 200 70545
WARNING 2025-08-25 04:39:16,295 log 22305 6148157440 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:39:16,295 basehttp 22305 6148157440 "GET /api/bin-data/ HTTP/1.1" 403 58
INFO 2025-08-25 04:39:16,299 basehttp 22305 6148157440 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 04:39:16,302 basehttp 22305 6148157440 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 04:40:04,122 autoreload 22305 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 04:40:04,571 autoreload 24041 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 04:40:14,112 autoreload 24041 8486575872 /Applications/smart-waste-management/waste_management/settings.py changed, reloading.
INFO 2025-08-25 04:40:14,414 autoreload 24321 8486575872 Watching for file changes with StatReloader
WARNING 2025-08-25 04:40:29,333 log 24321 6170832896 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:40:29,334 basehttp 24321 6170832896 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:40:29,336 log 24321 6170832896 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:40:29,336 basehttp 24321 6170832896 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:40:29,338 log 24321 6170832896 Forbidden: /api/trucks/
WARNING 2025-08-25 04:40:29,338 basehttp 24321 6170832896 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:40:48,878 log 24321 6170832896 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:40:48,878 basehttp 24321 6170832896 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:40:48,880 log 24321 6170832896 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:40:48,880 basehttp 24321 6170832896 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:40:48,882 log 24321 6170832896 Forbidden: /api/trucks/
WARNING 2025-08-25 04:40:48,882 basehttp 24321 6170832896 "GET /api/trucks/ HTTP/1.1" 403 58
INFO 2025-08-25 04:41:00,900 basehttp 24321 6170832896 "GET /admin/ HTTP/1.1" 200 70545
WARNING 2025-08-25 04:41:13,412 log 24321 6204485632 Forbidden: /api/bin-data/
WARNING 2025-08-25 04:41:13,412 basehttp 24321 6204485632 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:41:13,414 log 24321 6204485632 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 04:41:13,414 basehttp 24321 6204485632 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 04:41:13,416 log 24321 6204485632 Forbidden: /api/trucks/
WARNING 2025-08-25 04:41:13,416 basehttp 24321 6204485632 "GET /api/trucks/ HTTP/1.1" 403 58
WARNING 2025-08-25 14:58:40,320 log 24321 6170832896 Forbidden: /api/bin-data/
WARNING 2025-08-25 14:58:40,321 basehttp 24321 6170832896 "GET /api/bin-data/ HTTP/1.1" 403 58
WARNING 2025-08-25 14:58:40,324 log 24321 6170832896 Forbidden: /api/dumping-spots/
WARNING 2025-08-25 14:58:40,324 basehttp 24321 6170832896 "GET /api/dumping-spots/ HTTP/1.1" 403 58
WARNING 2025-08-25 14:58:40,326 log 24321 6170832896 Forbidden: /api/trucks/
WARNING 2025-08-25 14:58:40,326 basehttp 24321 6170832896 "GET /api/trucks/ HTTP/1.1" 403 58
INFO 2025-08-25 15:16:10,437 autoreload 24321 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:16:10,871 autoreload 47586 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:16:23,413 autoreload 47586 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:16:23,749 autoreload 47676 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:16:34,160 autoreload 47676 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:16:34,390 autoreload 47748 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:16:41,687 autoreload 47748 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:16:41,919 autoreload 47796 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:16:50,287 autoreload 47796 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:16:50,507 autoreload 47852 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:17:00,903 autoreload 47852 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:17:01,247 autoreload 47925 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:17:10,638 autoreload 47925 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:17:10,985 autoreload 47993 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:17:19,373 autoreload 47993 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:17:19,627 autoreload 48050 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:17:28,042 autoreload 48050 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:17:28,298 autoreload 48103 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:17:36,654 autoreload 48103 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:17:36,890 autoreload 48164 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:17:48,297 autoreload 48164 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:17:48,520 autoreload 48247 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 15:34:38,770 autoreload 48247 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 15:34:39,166 autoreload 54132 8486575872 Watching for file changes with StatReloader
WARNING 2025-08-25 19:13:38,962 log 54132 6131068928 Forbidden: /api/bin-data/
WARNING 2025-08-25 19:13:38,962 basehttp 54132 6131068928 "GET /api/bin-data/ HTTP/1.1" 403 58
INFO 2025-08-25 19:13:38,970 basehttp 54132 6131068928 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 19:13:38,976 basehttp 54132 6131068928 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 19:14:08,080 autoreload 54132 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:14:08,482 autoreload 31139 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:14:15,823 autoreload 31139 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:14:16,061 autoreload 31191 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:14:26,390 autoreload 31191 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:14:26,635 autoreload 31261 8486575872 Watching for file changes with StatReloader
WARNING 2025-08-25 19:14:36,639 log 31261 6131150848 Forbidden: /api/bin-data/
WARNING 2025-08-25 19:14:36,639 basehttp 31261 6131150848 "GET /api/bin-data/ HTTP/1.1" 403 58
INFO 2025-08-25 19:14:36,644 basehttp 31261 6131150848 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 19:14:36,648 basehttp 31261 6131150848 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 19:14:39,104 autoreload 31261 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:14:39,359 autoreload 31352 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:14:41,611 basehttp 31352 6170357760 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 19:14:41,637 basehttp 31352 6170357760 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 59062
INFO 2025-08-25 19:14:53,298 auth_backends 31352 6170357760 Successful login: admin from 127.0.0.1
INFO 2025-08-25 19:14:53,303 basehttp 31352 6170357760 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-08-25 19:14:53,316 basehttp 31352 6170357760 "GET /admin/ HTTP/1.1" 200 70545
INFO 2025-08-25 19:15:32,767 autoreload 31352 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:15:33,175 autoreload 31755 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:36:30,805 basehttp 31755 6162280448 "GET /admin/ HTTP/1.1" 200 70545
WARNING 2025-08-25 19:36:36,178 log 31755 6195933184 Forbidden: /api/bin-data/
WARNING 2025-08-25 19:36:36,178 basehttp 31755 6195933184 "GET /api/bin-data/ HTTP/1.1" 403 58
INFO 2025-08-25 19:36:36,183 basehttp 31755 6195933184 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 19:36:36,187 basehttp 31755 6195933184 "GET /api/trucks/ HTTP/1.1" 200 905
WARNING 2025-08-25 19:37:06,010 log 31755 6195933184 Forbidden: /api/bin-data/
WARNING 2025-08-25 19:37:06,010 basehttp 31755 6195933184 "GET /api/bin-data/ HTTP/1.1" 403 58
INFO 2025-08-25 19:37:06,013 basehttp 31755 6195933184 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 19:37:06,016 basehttp 31755 6195933184 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 19:37:15,741 autoreload 31755 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:37:16,096 autoreload 39853 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:37:39,835 autoreload 39853 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:37:40,061 autoreload 40006 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:37:54,553 autoreload 40006 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:37:54,775 autoreload 40101 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:38:06,257 autoreload 40101 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:38:06,508 autoreload 40170 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:38:24,134 autoreload 40170 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:38:24,372 autoreload 40287 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:38:37,870 autoreload 40287 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:38:38,107 autoreload 40370 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:39:01,874 autoreload 40370 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:39:02,092 autoreload 40517 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 19:40:06,971 autoreload 40517 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 19:40:07,213 autoreload 40906 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 21:13:05,957 autoreload 40906 8486575872 /Applications/smart-waste-management/core/views.py changed, reloading.
INFO 2025-08-25 21:13:06,211 autoreload 73435 8486575872 Watching for file changes with StatReloader
INFO 2025-08-25 21:13:56,731 views 73435 6121943040 Bin data retrieved by user: Anonymous
INFO 2025-08-25 21:13:56,734 basehttp 73435 6121943040 "GET /api/bin-data/ HTTP/1.1" 200 10983
INFO 2025-08-25 21:14:02,770 basehttp 73435 6121943040 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 21:14:06,255 basehttp 73435 6121943040 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 21:17:44,852 basehttp 73435 6121943040 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-08-25 21:17:44,875 basehttp 73435 6121943040 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 59062
INFO 2025-08-25 21:17:54,082 auth_backends 73435 6121943040 Successful login: admin from 127.0.0.1
INFO 2025-08-25 21:17:54,088 basehttp 73435 6121943040 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-08-25 21:17:54,104 basehttp 73435 6121943040 "GET /admin/ HTTP/1.1" 200 70545
INFO 2025-08-25 21:18:01,424 views 73435 6155595776 Bin data retrieved by user: Anonymous
INFO 2025-08-25 21:18:01,426 basehttp 73435 6155595776 "GET /api/bin-data/ HTTP/1.1" 200 10983
INFO 2025-08-25 21:18:01,429 basehttp 73435 6155595776 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 21:18:01,433 basehttp 73435 6155595776 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 21:19:00,839 views 73435 6138769408 Bin data retrieved by user: Anonymous
INFO 2025-08-25 21:19:00,842 basehttp 73435 6138769408 "GET /api/bin-data/ HTTP/1.1" 200 10983
INFO 2025-08-25 21:19:00,846 basehttp 73435 6138769408 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 21:19:00,849 basehttp 73435 6138769408 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 21:19:28,109 basehttp 73435 6138769408 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 21:19:44,173 views 73435 6138769408 Bin data retrieved by user: Anonymous
INFO 2025-08-25 21:19:44,176 basehttp 73435 6138769408 "GET /api/bin-data/ HTTP/1.1" 200 10983
INFO 2025-08-25 21:19:44,180 basehttp 73435 6138769408 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 21:19:44,183 basehttp 73435 6138769408 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 21:19:56,394 views 73435 6138769408 Bin data retrieved by user: Anonymous
INFO 2025-08-25 21:19:56,396 basehttp 73435 6138769408 "GET /api/bin-data/ HTTP/1.1" 200 10983
INFO 2025-08-25 21:19:56,399 basehttp 73435 6138769408 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 21:19:56,403 basehttp 73435 6138769408 "GET /api/trucks/ HTTP/1.1" 200 905
INFO 2025-08-25 21:20:05,315 basehttp 73435 6121943040 "GET /admin/ HTTP/1.1" 200 70545
INFO 2025-08-25 21:20:19,997 basehttp 73435 6155595776 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 21:21:47,588 basehttp 73435 6155595776 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 21:22:17,885 views 73435 6138769408 Bin data retrieved by user: Anonymous
INFO 2025-08-25 21:22:17,887 basehttp 73435 6138769408 "GET /api/bin-data/ HTTP/1.1" 200 10983
INFO 2025-08-25 21:22:17,890 basehttp 73435 6138769408 "GET /api/dumping-spots/ HTTP/1.1" 200 1187
INFO 2025-08-25 21:22:17,894 basehttp 73435 6138769408 "GET /api/trucks/ HTTP/1.1" 200 905
